---
name: "blackjack"

services:
  app:
    build:
      context: "../../"
      dockerfile: "./docker/dev/Dockerfile"
      args:
        - "ELIXIR_VERSION=1.16.0"
        - "USER_UID=${USER_UID:-1000}"
    working_dir: "/app"
    command: "mix phx.server"
    restart: "unless-stopped"
    user: "dev"
    tty: true
    stdin_open: true
    volumes:
      - type: "bind"
        source: "../../"
        target: "/app"
        read_only: false
    ports:
      - "4000:4000"
...
